package src.model;

public enum GameState {

	START_TITLE, MAIN_MENU, LOAD_GAME, PLAYING, SELECT_AVATAR, OPTIONS, COMMAND_EXPLAINATION, QUIT, TRANSITION_STATE, PAUSE, DIALOGUE, BOSS_CUTSCENE, GAME_OVER, END_GAME;

	public static GameState actualState = START_TITLE;

}


